# Site Settings
locale                   : "en-US"
title                    : "Sumit Kumar"
title_separator          : "-"
name                     : &name "Sumit Kumar"
description              : &description "my homepage"
url                      : https://sumitsk.github.io
baseurl                  : ""
repository               : "sumitsk.github.io"
future                   : true

# Site Author
author:
  name             : "Sumit Kumar"
  avatar           :
  bio              : "Staff Tech Lead Manager at Aurora Innovation"
  location         : "Mountain View, CA"
  email            : "sumit.sks4@gmail.com"
  googlescholar    : "https://scholar.google.com/citations?user=19zu0ZwAAAAJ&hl=en"
  github           : "sumitsk"
  linkedin         : "sumitsks4"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - LICENSE
  - README
  - tmp
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
